### ISSUE TITLE
Should we be doing another release soon?

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#153]
The list of changes is getting very lengthy.  A lot has happened in sccz80 especially.  I think we should consider doing a 1.99C release to keep the list manageable even though we are far from December 31.

If everyone agrees I think before that happens some things should be completed (feel free to add to it):

* [x] new c lib sms target completed (printf and a few minor items remain) (#145)
* [x] sccz80 SFRs completed (#78)
* [x] sccz80 --constseg and --codeseg compatibility with zsdcc completed (#155)
* [x] sccz80 sort out casting (#26)
* [x] classic c library transition to correct LF/CR in terminals completed (#136)
* [x] classic RCMXXX support completed (#135)
* [ ] classic argv wildcard parsing (#149)
* [ ] new c lib z180 target first pass completed (#50)
* [x] new c lib transition to SFRs for sccz80 (#152)
* [ ] new c lib re-examine zsdcc c interface for opportunities to use char rather than int function parameters (#21)  (maybe depending on time - there is a chance this will introduce bugs so there should be some time for testing)
* [x] new c lib update examples to use latest pragmas
* [x] new c lib clean up z80.h and z180.h given changes
* [ ] benchmarks: complete most of them and tidy up the ones that are finished (#111)
* [ ] update sms example space hawks

Too soon or good idea?

**Comment by suborb** [comment]
Yes, this moving to GitHub thing really did give us a bit of impetus! 

Probably best to drop multi-dim arrays out of the candidate features, I've not had a chance to look at how to do it yet, but my gut says that I'm not going to enjoy it that much!

I'm all for a new release, I've been roughly keeping changelog.txt up-to-date and it's already quite long with just the classic and sccz80 changes.

**Comment by pauloscustodio** [comment]
I agree with a release.

The new z80asm is still a long way to complete.

**Comment by zx70** [comment]
I understand it will take a bit more but I'd like to have the classic lib adjusted as for #136 . 
It will permit sdcc to be used with most of the targets:  adjusting the code is not a long work but testing/revisioning all the targets takes more than expected.

**Comment by suborb** [comment]
@aralbrec given the time of year, I guess it's almost time for another christmas present?

**Comment by aralbrec** [comment]
Yeah it looks like we missed the mid-year deadline.  I think whatever we have for December will be it.

**Comment by feilipu** [comment]
1.99c ?
