### ISSUE TITLE
Candidate items for v2.3 Release

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#2371]
It has been a year since v2.2, so,...

An open list for things which might be added before the v2.3 Release.
Please __edit__, add or exclude as relevant or desired...

Or we could open a [project](https://github.com/z88dk/z88dk/projects?type=classic) with the proposed list?

- [ ] ZX0 #1864
- [x] Aquarius+ #2352 #2064
- [x] Parallel build support #2331
- [x] ez80-clang as compiler #2329
- [ ] homebrew package for v2.3 #1633
- [x] do not link different cpu #2320
- [x] ucpp macros #2385 
- [x] z88dk macros #2384 

- [x] debian / Ubuntu i386 release package #2372

For @feilipu 
- [x] Integer maths Rabbit r2ka 64_64x64 https://github.com/z88dk/z88dk/commit/2682c8c03a5df1c873a2e21a4f29fa155a59c7a1
- [x] math32 Rabbit r2ka optimisation https://github.com/z88dk/z88dk/commit/de5746f02d514376e05fafb2ba76f6f4e66d7b0e (added  z180, z80n, r2ka to the tests https://github.com/z88dk/z88dk/commit/feb81e00570e35c14359134cf8cc0d76d4b017c0)

Would it be best to push #1391 out to v2.4 or a v3.0 (even though it was already in the [v2.2 todo](https://github.com/z88dk/z88dk/projects/4#card-32558393) :wink:), and have a simple Release before tackling the big job?

**Comment by suborb** [comment]
Thanks for doing this - it probably is about time again.

* Clang: I think this is done enough for now. There's enough library support to be useful and I've not seen any feedback on it.
* Parallel builds: The immediate problem was sorted, newlib is parallelised, classic should be as well. 
* Aquarius+: I just need to implement `opendir` and friends here.

#1391 should be kicked out again (I'll comment on that issue later)

The one thing that would be nice (but is a big change with possibly lots of issues) is #2320

**Comment by pauloscustodio** [comment]
I'm finishing #2338 and will tackle #2320 next.

**Comment by zx70** [comment]
There's a couple of issues I totally left behind, which obviously can stay like this a little more.   The TI calculator issue is probably slightly pointless, IIRC the native asm() entry allows very small programs only.
As for the bug on the Aquarius we should find someone owning the hardware and coordinating the tests.

**Comment by feilipu** [comment]
> As for the bug on the Aquarius we should find someone owning the hardware and coordinating the tests.

@Fabrizio-Caruso suggested that Roy Templeman (@LoudScotsBloke) might be able to help, if he's listening?

**Comment by pauloscustodio** [comment]
> The one thing that would be nice (but is a big change with possibly lots of issues) is #2320

The feature is ready in the issue_2320 branch, but the library does not build, due to incompatible -IXIY options between objects being linked together.

**Comment by pauloscustodio** [comment]
On issue #2320: on the issue_2320 branch you cannot include in a library an object file built for a different CPU.
As a possible solution I've added the options "z80asm -m'*' -xlib ,,," that assembles all files for all CPU-IXIY combinations and packs them all in the same library; when linking, z80asm skips the object files for a different architecture and all should work.

**Comment by zx70** [comment]
> Hi guys, I'm listening! What would you like me to do?

Roy,
You're very kind showing up immediately!
I left a couple of issues pending related to the Mattel Aquarius, I wonder if it's possible for you to do some testing on the real machine ?

Is redirect you to a proper issue chat

**Comment by feilipu** [comment]
@LoudScotsBloke is this issue https://github.com/z88dk/z88dk/issues/2064 still current with the current code?

**Comment by feilipu** [comment]
Added math32 r2ka tests... some useful numbers. Even if not fully optimised, I think it will do.

```sh

zcc +test -vn  -DMATH32 -D__MATH_MATH32 -fp-mode=ieee -DMATH_LIBRARY="\"\\\"Math32\\\"\"" -I../../framework -DNO_LOG_RUNNING -DNO_LOG_PASSED  ../../framework/test.c math.c -o test_math32.bin  -lmath32 -m
 21:04:05  Starting test 
Starting suite Math32 Tests (13 tests)
13 run, 13 passed, 0 failed

Ticks: 9959656
 21:04:05  Test completed 
zcc +test -vn -clib=z180  -DMATH32 -D__MATH_MATH32 -fp-mode=ieee -DMATH_LIBRARY="\"\\\"Math32\\\"\"" -I../../framework -DNO_LOG_RUNNING -DNO_LOG_PASSED  ../../framework/test.c math.c -o test_math32_z180.bin   -lmath32_z180 -m
 21:04:06  Starting z180 test 
Starting suite Math32 Tests (13 tests)
13 run, 13 passed, 0 failed

Ticks: 6994100
 21:04:06  z180 test completed 
zcc +test -vn -clib=z80n  -DMATH32 -D__MATH_MATH32 -fp-mode=ieee -DMATH_LIBRARY="\"\\\"Math32\\\"\"" -I../../framework -DNO_LOG_RUNNING -DNO_LOG_PASSED  ../../framework/test.c math.c -o test_math32_z80n.bin   -lmath32_z80n -m
 21:04:06  Starting Z80N test 
Starting suite Math32 Tests (13 tests)
13 run, 13 passed, 0 failed

Ticks: 7618557
 21:04:06  Z80N test completed 
zcc +test -vn -clib=rabbit  -DMATH32 -D__MATH_MATH32 -fp-mode=ieee -DMATH_LIBRARY="\"\\\"Math32\\\"\"" -I../../framework -DNO_LOG_RUNNING -DNO_LOG_PASSED  ../../framework/test.c math.c -o test_math32_r2ka.bin   -lmath32_r2ka -m
 21:04:08  Starting Rabbit test 
Starting suite Math32 Tests (13 tests)
13 run, 13 passed, 0 failed

Ticks: 5335774
 21:04:08  Rabbit test completed 
```

**Comment by suborb** [comment]
Things have slowed down again. I’m minded to do a snapshot and release around about the 15th December  - any objections?

**Comment by suborb** [comment]
Smidgen delayed on this one (let's say the 15th crept up on me). 

Now the s390 stuff is resolved, I want to get #2461 in and #2462 confirmed as fixed.

**Comment by suborb** [comment]
Snapshotted and released.

**Comment by feilipu** [comment]
Note to adjust main `README.md` to potato new release.

**Comment by zx70** [comment]
Congrats Dom, this autumn you kept parallelizing several issues.   Impressive !
